import { describe, it, expect, vi, beforeEach } from 'vitest';

const { mockFetch } = vi.hoisted(() => ({ mockFetch: vi.fn() }));
vi.mock('node-fetch', () => ({ default: mockFetch }));

// Mock config so we can control provider/key per test
vi.mock('../config', () => ({
  config: {
    llmProvider: 'offline',
    llmApiUrl: '',
    llmApiKey: 'test-key',
    llmModel: '',
    platformBase: '',
    platformKey: '',
    botAuthor: 'TestBot',
    botTone: 'informal',
  },
  resolveModel: () => 'gpt-4o-mini',
  resolveApiUrl: () => 'https://api.openai.com/v1/chat/completions',
}));

import { generatePost } from '../generator';
import { config } from '../config';

beforeEach(() => {
  vi.clearAllMocks();
  (config as any).llmProvider = 'offline';
});

describe('generatePost', () => {
  it('returns demo content in offline mode', async () => {
    const result = await generatePost('Tell me about ai');
    expect(result).toContain('Context Windows');
  });

  it('returns default demo content for unknown topic', async () => {
    const result = await generatePost('something random');
    expect(result).toContain('Autonomous Agents');
  });

  it('calls OpenAI-compatible endpoint when provider is openai', async () => {
    (config as any).llmProvider = 'openai';
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        choices: [{ message: { content: 'Generated by OpenAI' } }],
      }),
    });

    const result = await generatePost('test prompt');
    expect(result).toBe('Generated by OpenAI');
    expect(mockFetch).toHaveBeenCalledOnce();

    const [url, opts] = mockFetch.mock.calls[0];
    expect(url).toBe('https://api.openai.com/v1/chat/completions');
    expect(opts.headers['Authorization']).toBe('Bearer test-key');
    const body = JSON.parse(opts.body);
    expect(body.messages[0].content).toBe('test prompt');
  });

  it('calls Anthropic endpoint when provider is anthropic', async () => {
    (config as any).llmProvider = 'anthropic';
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        content: [{ text: 'Generated by Anthropic' }],
      }),
    });

    const result = await generatePost('test prompt');
    expect(result).toBe('Generated by Anthropic');
  });

  it('throws on non-ok response from openai', async () => {
    (config as any).llmProvider = 'openai';
    mockFetch.mockResolvedValueOnce({
      ok: false,
      status: 401,
      text: async () => 'Unauthorized',
    });

    await expect(generatePost('test')).rejects.toThrow('OpenAI error: 401');
  });

  it('throws on non-ok response from anthropic', async () => {
    (config as any).llmProvider = 'anthropic';
    mockFetch.mockResolvedValueOnce({
      ok: false,
      status: 500,
      text: async () => 'Internal Server Error',
    });

    await expect(generatePost('test')).rejects.toThrow('Anthropic error: 500');
  });
});
